# Generated by Django 2.2 on 2019-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicels_titles', models.CharField(max_length=100)),
                ('daily_rent', models.DecimalField(decimal_places=0, max_digits=5)),
                ('weekly_rent', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fifteen_day_rent', models.DecimalField(decimal_places=0, max_digits=5)),
                ('monthly_rent', models.DecimalField(decimal_places=0, max_digits=5)),
                ('features', models.TextField()),
                ('car_category', models.CharField(choices=[('cr', 'Cars'), ('lx', 'luxury'), ('suv', 'SUV'), ('vn', 'Vans & Buses')], default='cr', max_length=2)),
            ],
        ),
    ]
