# Generated by Django 2.2 on 2019-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicel',
            old_name='vehicels_titles',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vehicel',
            name='features',
        ),
        migrations.AddField(
            model_name='vehicel',
            name='color',
            field=models.CharField(default='black', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='image1',
            field=models.FilePathField(default='/img', path='/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='image2',
            field=models.FilePathField(default='/img', path='/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='image3',
            field=models.FilePathField(default='/img', path='/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='image4',
            field=models.FilePathField(default='/img', path='/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='make',
            field=models.CharField(default='Toyota', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicel',
            name='year',
            field=models.CharField(default='2018', max_length=100),
            preserve_default=False,
        ),
    ]
