# Generated by Django 2.2.2 on 2019-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicels', '0002_auto_20190501_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel',
            name='image1',
            field=models.FilePathField(path='/static/img'),
        ),
        migrations.AlterField(
            model_name='vehicel',
            name='image2',
            field=models.FilePathField(path='/static/img'),
        ),
        migrations.AlterField(
            model_name='vehicel',
            name='image3',
            field=models.FilePathField(path='/static/img'),
        ),
        migrations.AlterField(
            model_name='vehicel',
            name='image4',
            field=models.FilePathField(path='/static/img'),
        ),
    ]
